### ISSUE TITLE
Not fully working

### ISSUE THREAD

**Issue by abreuof** [GitHixy/GitHixy-SND-Scripts#1]
The script enters the race but after that it stops working. It does not press W and does not enter any races again.

**Comment by GitHixy** [comment]
Please be more specific, it fully works for me and other testers, check /xllogs for any errors, could be some wait timers to adjust for your config.
Let me know

**Comment by abreuof** [comment]
08:53:55.159 | INF | [SomethingNeedDoing] looking for non party member target
08:53:55.159 | WRN | "Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.
08:54:28.251 | WRN | "Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.
08:54:28.251 | INF | [vnavmesh] Queueing move-to <-4,820. 1,040. 2,210>
08:54:28.272 | INF | [vnavmesh] Pathfinding complete
08:54:42.258 | INF | [vnavmesh] Queueing move-to <-7,570. -1,780. -67,540>
08:54:42.282 | INF | [vnavmesh] Pathfinding complete
08:54:52.262 | INF | [SomethingNeedDoing] looking for non party member target
08:54:56.564 | INF | [vnavmesh] Queueing move-to <-3,970. -2,020. -65,440>
08:54:56.586 | INF | [vnavmesh] Pathfinding complete
08:54:57.564 | INF | [SomethingNeedDoing] looking for non party member target
08:54:58.564 | WRN | "Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.
08:55:02.265 | INF | [vnavmesh] Queueing move-to <-3,970. -2,020. -65,440>
08:55:02.283 | INF | [vnavmesh] Pathfinding complete
08:55:03.265 | INF | [SomethingNeedDoing] looking for non party member target
08:55:28.721 | WRN | "Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.

also: The command /li Chocobo Square does not exist

**Comment by GitHixy** [comment]
> 08:53:55.159 | INF | [SomethingNeedDoing] looking for non party member target
> 
> 08:53:55.159 | WRN | "Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.
> 
> 08:54:28.251 | WRN | "Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.
> 
> 08:54:28.251 | INF | [vnavmesh] Queueing move-to <-4,820. 1,040. 2,210>
> 
> 08:54:28.272 | INF | [vnavmesh] Pathfinding complete
> 
> 08:54:42.258 | INF | [vnavmesh] Queueing move-to <-7,570. -1,780. -67,540>
> 
> 08:54:42.282 | INF | [vnavmesh] Pathfinding complete
> 
> 08:54:52.262 | INF | [SomethingNeedDoing] looking for non party member target
> 
> 08:54:56.564 | INF | [vnavmesh] Queueing move-to <-3,970. -2,020. -65,440>
> 
> 08:54:56.586 | INF | [vnavmesh] Pathfinding complete
> 
> 08:54:57.564 | INF | [SomethingNeedDoing] looking for non party member target
> 
> 08:54:58.564 | WRN | "Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.
> 
> 08:55:02.265 | INF | [vnavmesh] Queueing move-to <-3,970. -2,020. -65,440>
> 
> 08:55:02.283 | INF | [vnavmesh] Pathfinding complete
> 
> 08:55:03.265 | INF | [SomethingNeedDoing] looking for non party member target
> 
> 08:55:28.721 | WRN | "Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.
> 
> 
> 
> also: The command /li Chocobo Square does not exist

You should install Lifestream so you can use aethernet with that command.
Basically the script is trying to reach destination but can't.
I should mention the required plugin in the config settings, will fix that asap.

**Comment by abreuof** [comment]
It opens my inventory but wont use the feed, and then: 
[SND] Failure while running  (step 50): Addon GoldSaucerInfo not found.

**Comment by GitHixy** [comment]
> It opens my inventory but wont use the feed, and then: 
> 
> [SND] Failure while running  (step 50): Addon GoldSaucerInfo not found.

Food selection in inventory may take a while because it need to cycle every slot and every tab.

I suggest to adjust wait timers because GoldSaucerInfo not found sounds like it does not have the time to get the data from there.

It kinda sucks but workarounds are needed for now. 

I'll close issue because in next versions many things will be updated and reworked, feel free to contact me on Discord - hixy1992 to work on your specific case.
Thanks
