### ISSUE TITLE
The script crashes the game

### ISSUE THREAD

**Issue by Shi974** [GitHixy/GitHixy-SND-Scripts#2]
Hello,
First of all, thanks for your script!
I have a French client so I modified line 319 to match the French version of the random chocobo race duty :

`if GetNodeText("ContentsFinder", 14) == "Course de chocobos : aléatoire" then`

The scripts works as intended, meaning : open Gold Saucer window, check if there are any training session left, queue in random race, do the race, have the /echo text when the race is over and XP rewards. At this point, it crashes my game. 
I only ran the script twice on two different days and it happened to me both times.
I will do another try next time I have to log out of the game to give more details like what's the last /echo message that was sent to chat to try to pinpoint exactly where the script fails.

I did not see any other users report some kind of error so my guess is maybe this is linked to the French client ?

**Comment by GitHixy** [comment]
> Hello,
> 
> First of all, thanks for your script!
> 
> I have a French client so I modified line 319 to match the French version of the random chocobo race duty :
> 
> 
> 
> `if GetNodeText("ContentsFinder", 14) == "Course de chocobos : aléatoire" then`
> 
> 
> 
> The scripts works as intended, meaning : open Gold Saucer window, check if there are any training session left, queue in random race, do the race, have the /echo text when the race is over and XP rewards. At this point, it crashes my game. 
> 
> I only ran the script twice on two different days and it happened to me both times.
> 
> I will do another try next time I have to log out of the game to give more details like what's the last /echo message that was sent to chat to try to pinpoint exactly where the script fails.
> 
> 
> 
> I did not see any other users report some kind of error so my guess is maybe this is linked to the French client ? 

Hi and thanks for the feedback, since the release of 7.1 the way we're interacting with tha game may have changed and I still didn't try the script, I'll look for it asap.
There're points where it is not perfect and stable.
Feel free to contact me on Discord: hixy1992
